// packages/solid-ui/src/components/Counter.tsx
import { createSignal } from "solid-js"
import { noShadowDOM } from "solid-element"

export const Counter = (props: { name: string }) => {
  noShadowDOM()

  const [count, setCount] = createSignal(0)

  return (
    <>
      <button onClick={() => setCount(count() + 1)}>Count: {count()}</button>
    </>
  )
}

// apps/astro/src/components/Counter.tsx
// import './Counter.css';

import { useState } from 'react'

export default function Counter({ children, count: initialCount }: { children: JSX.Element; count: number }) {
  const [count, setCount] = useState(initialCount)
  const add = () => setCount(i => i + 1)
  const subtract = () => {
    setCount(i => i - 1)
    console.log('subtract')
  }

  return (
    <>
      <div className="counter">
        <button onClick={subtract}>-</button>
        <pre>{count}</pre>
        <button onClick={add}>+</button>
      </div>
      <div className="counter-message">{children}</div>
    </>
  )
}
