// apps/react/src/App.tsx
/* eslint-disable @next/next/no-img-element */
import './App.css'
import '@roboncode/lit-ui'
import '@roboncode/solid-ui'
import '@roboncode/svelte-ui'

import reactLogo from './assets/react.svg'
import { useState } from 'react'

function App() {
  const [count, setCount] = useState(0)
  const [name, setName] = useState<string>('React')
  
  return (
    <div className="App">
      <div>
        <a href="https://vitejs.dev" target="_blank" rel="noreferrer">
          <img src="/vite.svg" className="logo" alt="Vite logo" />
        </a>
        <a href="https://reactjs.org" target="_blank" rel="noreferrer">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>

      <lit-counter name={name} onClick={() => setName('world')} class="block font-bold p-4 bg-shade rounded-md" />
      <solid-counter name={name} onClick={() => setName('world')} class="block font-bold p-4 bg-shade rounded-md" />
      <svelte-counter name={name} onClick={() => setName('world')} class="block font-bold p-4 bg-shade rounded-md" />

    </div>
  )
}

export default App

// packages/svelte-ui/src/App.svelte
<svelte:options tag={null} />

<script lang="ts">
  import svelteLogo from './assets/svelte.svg'
  // import Counter from './lib/Counter.svelte'
</script>

<main>
  <div>
    <a href="https://vitejs.dev" target="_blank"> 
      <img src="/vite.svg" class="logo" alt="Vite Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank"> 
      <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
    </a>
  </div>
  <h1>Vite + Svelte</h1>

  <!-- <div class="card">
    <Counter />
  </div> -->

  <p>
    Check out <a href="https://github.com/sveltejs/kit#readme" target="_blank">SvelteKit</a>, the official Svelte app framework powered by Vite!
  </p>

  <p class="read-the-docs">
    Click on the Vite and Svelte logos to learn more
  </p>
</main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }
  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  }
  .read-the-docs {
    color: #888;
  }
</style>
